# config.py

SOURCE_DIR = 'data/'
CSV_FILE = 'plant_labels.csv'
NPY_FILE = 'plant_images.npy'

# Generic (used primarily for Conv2D Filters)
XXLG_CNT = 512
XLG_CNT = 256
LG_CNT = 128
MED_CNT = 64
SM_CNT = 32
XSM_CNT = 16
SEED = 42

# Time
MSEC = 1000
SECS_IN_MIN = 60

# Data Split Percentages
TEMPORARY_DATA_SPLIT = 0.2
TRAINING_DATA_SPLIT = 0.8
TESTING_DATA_SPLIT = 0.1
VALIDATION_DATA_SPLIT = 0.1
HALF_DATA_SPLIT = 0.5

# Image Data
IMAGE_CHANNELS = 3
IMAGE_PX_MAX = 255.0
IMAGE_ROWS = IMAGE_COLS = 4

# Models
DA_LEARNING_RATE = 1e-4
#TL_LEARNING_RATE = 1e-5
TL_LEARNING_RATE = 1e-3
DROPOUT_RATE = 0.5
L2_LEARNING_RATE = 1e-7
#L2_REGRESSION_RATE = 0.01

# Conv2D
KERNEL_SIZE_MED = (3, 3)
KERNEL_SIZE_SM = (2, 2)

# Base Model Fit
BASE_EPOCH_CNT = 30
BASE_BATCH_SIZE = 64
GENERATOR_BATCH_SIZE = 48

# Trained Model Fit
TRAINED_EPOCH_CNT = 36
TRAINED_BATCH_SIZE = 32
